GET http://localhost:3000/songs.json

###

POST http://localhost:3000/songs.json
content-type: application/json

{

  "title": "First title",
  "artist": "first artist",
  "album": "album number one",
  "year": "1997"


}
###
GET http://localhost:3000/songs/3.json